# Generated by Django 3.1.2 on 2020-10-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=120, null=True)),
                ('channel_username', models.CharField(max_length=120, null=True)),
                ('channel_name', models.CharField(max_length=120, null=True)),
                ('subscriber_count', models.BigIntegerField(null=True)),
                ('video_count', models.BigIntegerField(null=True)),
                ('total_streaming_time', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=120)),
                ('searched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=120, null=True)),
                ('video_title', models.CharField(max_length=200, null=True)),
                ('view_count', models.BigIntegerField(null=True)),
                ('likes', models.BigIntegerField(null=True)),
                ('dislikes', models.BigIntegerField(null=True)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.channel')),
            ],
        ),
    ]
