# Generated by Django 3.1.2 on 2020-10-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20201001_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='total_streaming_time',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_photo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='country',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='view_count',
            field=models.BigIntegerField(null=True),
        ),
    ]
