# Generated by Django 3.1.2 on 2020-10-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20201006_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searched_at',
            field=models.DateTimeField(),
        ),
    ]
